import laptop from '../Images/270400_0_eozmri.jpeg'
import laptop1 from '../Images/laptop1.jpeg'
import laptop2 from '../Images/laptop2.jpeg'
import laptop3 from '../Images/laptop3.jpeg'
import laptop4 from '../Images/laptop4.jpeg'
import laptop5 from '../Images/laptop5.jpeg'
import laptop6 from '../Images/laptop6.jpeg'
import laptop7 from '../Images/laptop7.jpeg'
import laptop8 from '../Images/laptop8.jpeg'
import laptop9 from '../Images/laptop9.jpeg'
import tv1 from '../Images/tv1.jpeg'
import tv2 from '../Images/tv2.jpeg'
import tv3 from '../Images/tv3.jpeg'
import tv4 from '../Images/tv4.jpeg'
import tv5 from '../Images/tv5.jpeg'
import tv6 from '../Images/tv6.jpeg'
import tv7 from '../Images/tv7.jpeg'
import tv8 from '../Images/tv8.jpeg'
import tv9 from '../Images/tv9.jpeg'
import tv10 from '../Images/tv10.jpeg'
import mb1 from '../Images/mb1.jpeg'
import mb2 from '../Images/mb2.jpeg'
import mb3 from '../Images/mb3.jpeg'
import mb4 from '../Images/mb4.jpeg'
import mb5 from '../Images/mb5.jpeg'
import mb6 from '../Images/mb6.jpeg'
import mb7 from '../Images/mb7.jpeg'
import mb8 from '../Images/mb8.jpeg'
import mb9 from '../Images/mb9.jpeg'
import mb10 from '../Images/mb10.jpeg'
import cm1 from '../Images/cm1.jpeg'
import cm2 from '../Images/cm2.jpeg'
import cm3 from '../Images/cm3.jpeg'
import cm4 from '../Images/cm4.jpeg'
import cm5 from '../Images/cm5.jpeg'
import cm6 from '../Images/cm6.jpeg'
import cm7 from '../Images/cm7.jpeg'
import cm8 from '../Images/cm8.jpeg'
import cm9 from '../Images/cm9.jpeg'
import cm10 from '../Images/cm10.jpeg'
import courel1 from '../Images/Corel1.jpeg'
import courel2 from '../Images/Corel2.jpeg'
import courel3 from '../Images/Corel3.jpeg'
import clogo from '../Images/image-removebg-preview.png'





export const Multimedia ={
    laptop,laptop1,laptop2,laptop3,laptop4,laptop5,laptop6,laptop7,laptop8,laptop9,tv1,tv2,tv3,tv4,tv5,tv6,tv7,tv8,tv9,tv10,mb1,mb2,mb3,mb4,mb5,mb6,mb7,mb8,mb9,mb10,cm1,cm2,cm3,cm4,cm5,cm6,cm7,cm8,cm9,cm10,courel1,courel2,courel3,clogo
}
